{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "links": {"attachments": {"href": "data/repositories/osrf/sdformat/issues/152/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/sdformat/issues/152.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/issues/152/watch"}, "comments": {"href": "data/repositories/osrf/sdformat/issues/152/comments_page=1.json"}, "html": {"href": "#!/osrf/sdformat/issues/152/segmentation-fault-in-sdf"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/sdformat/issues/152/vote"}}, "reporter": {"display_name": "Dominic Jud", "uuid": "{a54b8beb-ec3d-4d25-9eb1-9c1032c013ef}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Ba54b8beb-ec3d-4d25-9eb1-9c1032c013ef%7D"}, "html": {"href": "https://bitbucket.org/%7Ba54b8beb-ec3d-4d25-9eb1-9c1032c013ef%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2aae58ebf3b8210e14699f18ebdb7dd7d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsDJ-6.png"}}, "nickname": "djud", "type": "user", "account_id": "557058:7220a58c-7c69-4eba-90e7-e61456907af1"}, "title": "Segmentation Fault in sdf::getBestSupportedModelVersion", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Since the last update of sdformat4, there is a segmentation fault occurring that was not there before the update. I'm using gazebo7 and Ubuntu 14.04. The backtrace goes to sdf::getBestSupportedModelVersion.\r\n\r\nLog with the backtrace from GDB when running gazebo:\r\n```\r\nProgram received signal SIGSEGV, Segmentation fault.\r\nstrlen () at ../sysdeps/x86_64/strlen.S:106\r\n106\t../sysdeps/x86_64/strlen.S: No such file or directory.\r\n(gdb) bt\r\n#0  strlen () at ../sysdeps/x86_64/strlen.S:106\r\n#1  0x00007ffff4eaf485 in sdf::getBestSupportedModelVersion(TiXmlElement*, std::string&) ()\r\n   from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#2  0x00007ffff4eafaae in sdf::getModelFilePath(std::string const&) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#3  0x00007ffff4eb7a7d in sdf::readXml(TiXmlElement*, std::shared_ptr<sdf::Element>) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#4  0x00007ffff4eb54ec in sdf::readXml(TiXmlElement*, std::shared_ptr<sdf::Element>) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#5  0x00007ffff4eb7ff4 in sdf::readDoc(TiXmlDocument*, std::shared_ptr<sdf::SDF>, std::string const&) ()\r\n   from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#6  0x00007ffff4eb89d8 in sdf::readFile(std::string const&, std::shared_ptr<sdf::SDF>) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\r\n#7  0x00007ffff7baedb4 in gazebo::Server::LoadFile(std::string const&, std::string const&) ()\r\n   from /usr/lib/x86_64-linux-gnu/libgazebo.so.7\r\n#8  0x00007ffff7bb088c in gazebo::Server::ParseArgs(int, char**) () from /usr/lib/x86_64-linux-gnu/libgazebo.so.7\r\n#9  0x00000000004024c9 in ?? ()\r\n#10 0x00007ffff6890f45 in __libc_start_main (main=0x4023e0, argc=10, argv=0x7fffffffc268, init=<optimized out>, fini=<optimized out>, \r\n    rtld_fini=<optimized out>, stack_end=0x7fffffffc258) at libc-start.c:287\r\n#11 0x0000000000402a38 in _start () \r\n```\r\n@scpeters As the author of the related PR: Is this a general bug or might it be a problem specific to me?", "markup": "markdown", "html": "<p>Since the last update of sdformat4, there is a segmentation fault occurring that was not there before the update. I'm using gazebo7 and Ubuntu 14.04. The backtrace goes to sdf::getBestSupportedModelVersion.</p>\n<p>Log with the backtrace from GDB when running gazebo:</p>\n<div class=\"codehilite\"><pre><span></span>Program received signal SIGSEGV, Segmentation fault.\nstrlen () at ../sysdeps/x86_64/strlen.S:106\n106 ../sysdeps/x86_64/strlen.S: No such file or directory.\n(gdb) bt\n#0  strlen () at ../sysdeps/x86_64/strlen.S:106\n#1  0x00007ffff4eaf485 in sdf::getBestSupportedModelVersion(TiXmlElement*, std::string&amp;) ()\n   from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#2  0x00007ffff4eafaae in sdf::getModelFilePath(std::string const&amp;) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#3  0x00007ffff4eb7a7d in sdf::readXml(TiXmlElement*, std::shared_ptr&lt;sdf::Element&gt;) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#4  0x00007ffff4eb54ec in sdf::readXml(TiXmlElement*, std::shared_ptr&lt;sdf::Element&gt;) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#5  0x00007ffff4eb7ff4 in sdf::readDoc(TiXmlDocument*, std::shared_ptr&lt;sdf::SDF&gt;, std::string const&amp;) ()\n   from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#6  0x00007ffff4eb89d8 in sdf::readFile(std::string const&amp;, std::shared_ptr&lt;sdf::SDF&gt;) () from /usr/lib/x86_64-linux-gnu/libsdformat.so.4\n#7  0x00007ffff7baedb4 in gazebo::Server::LoadFile(std::string const&amp;, std::string const&amp;) ()\n   from /usr/lib/x86_64-linux-gnu/libgazebo.so.7\n#8  0x00007ffff7bb088c in gazebo::Server::ParseArgs(int, char**) () from /usr/lib/x86_64-linux-gnu/libgazebo.so.7\n#9  0x00000000004024c9 in ?? ()\n#10 0x00007ffff6890f45 in __libc_start_main (main=0x4023e0, argc=10, argv=0x7fffffffc268, init=&lt;optimized out&gt;, fini=&lt;optimized out&gt;, \n    rtld_fini=&lt;optimized out&gt;, stack_end=0x7fffffffc258) at libc-start.c:287\n#11 0x0000000000402a38 in _start () \n</pre></div>\n\n\n<p>@scpeters As the author of the related PR: Is this a general bug or might it be a problem specific to me?</p>", "type": "rendered"}, "assignee": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2017-03-22T10:25:44.998263+00:00", "milestone": null, "updated_on": "2017-03-24T12:20:53.608966+00:00", "type": "issue", "id": 152}